memcached:
  enabled: false
mariadb:
  enabled: true
wordpress:
  wordpressUsername: admin
  wordpressPassword: cj900dsm0cjkeOII
  wordpressFirstName: Admin
  wordpressLastName: User
  wordpressBlogName: A Wordpress Blog
  wordpressPlugins: none
  replicaCount: 1
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: wordpress.weavegitops.com
    path: /?(.*)
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      nginx.ingress.kubernetes.io/service-upstream: "true"
    tls: true
  persistence:
    enabled: true
    storageClass: default
    accessMode: ReadWriteMany
    size: 2Gi
  metrics:
    enabled: true
  mariadb:
    architecture: standalone
    auth:
      rootPassword: asd3409if23409
      replicationPassword: asdfko89u35
      password: icei4jdio&js
    primary:
      persistence:
        storageClass: default
        size: 2Gi
