apiVersion: v2
name: podinfo
description: A Weaveworks Helm chart for podinfo
type: application
version: 0.0.5
appVersion : 2.1.0
kubeVersion: ">=1.16.0-0"
home: https://github.com/weavegitops/app-charts
sources:
  - https://github.com/stefanprodan/podinfo

annotations:
  "weave.works/profile": podinfo
  "weave.works/category": Application
  "weave.works/links": |
    - name: Chart Sources
      url: https://github.com/weavegitops/app-charts
    - name: Upstream Project
      url: https://github.com/stefanprodan/podinfo

maintainers:
  - name: "Lutz Lange"
    email: lutz@weave.works
